services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
  rep_p:
    build: 
      context: ./rep_primary
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rep_p:/var/lib/mysql
    ports:
      - 13306:3306
  rep_s:
    build: 
      context: ./rep_secondary
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - rep_s:/var/lib/mysql
    ports:
      - 23306:3306
  db-tuner:
    build: 
      context: ./db-tuner
      dockerfile: Dockerfile
    links:
      - db
volumes:
  db-store:
  rep_p:
  rep_s:
